### PR TITLE
End poin mentees user ban status andrii

### PR DESCRIPTION
**Pull request by AndriyGu**

### CODE REVIEW

**Review by OleksandRomaniuk — COMMENTED** [review]
+

**Review by worktvv — APPROVED** [review]

**Review by zbohdan349 — APPROVED** [review]

**Review by OleksandRomaniuk — COMMENTED** [review]
+

**Review by OleksandRomaniuk — COMMENTED** [review]
+

**Review by OleksandRomaniuk — COMMENTED** [review]
+

**Review by OleksandRomaniuk — COMMENTED** [review]
+

**Review by OleksandRomaniuk — COMMENTED** [review]
+

**Review by OleksandRomaniuk — COMMENTED** [review]
+

**Review by OleksandRomaniuk — COMMENTED** [review]
+

**Review by OleksandRomaniuk — COMMENTED** [review]
+

**Review by OleksandRomaniuk — COMMENTED** [review]
+

**Review by OleksandRomaniuk — COMMENTED** [review]
+

**Review by AndriiPanchyshyn — APPROVED** [review]

**Pull request merged**
